version: "3.7"

x-service-volumes: &service-volumes
  - ./:/app/:rw,cached

services:
  website:
    image: crypto_board_docker:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes: *service-volumes
    ports:
      - "8000:8000"